name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: avaliacao-outsera-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Playwright API + Cucumber E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers and system deps
        run: npx playwright install --with-deps

      - name: Run Playwright API tests (with GitHub + HTML reporters)
        run: npx playwright test tests/api/ --reporter=github,html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: warn

      - name: Run Cucumber features (BDD)
        id: cucumber
        continue-on-error: true
        run: npx cucumber-js

      - name: Upload Cucumber JSONs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json
          path: |
            cucumber-report-*.json
          if-no-files-found: warn

      - name: Upload Cucumber HTML (custom)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html
          path: test-results/cucumber-html-report.html
          if-no-files-found: warn

      - name: Job summary
        if: always()
        run: |
          {
            echo "## ✅ CI executado";
            echo;
            echo "- Branch: $GITHUB_REF";
            echo "- Commit: $GITHUB_SHA";
            echo;
            if [ "${{ steps.cucumber.outcome }}" == "failure" ]; then
              echo "⚠️ **Atenção**: Cucumber teve falhas de cenário. Verifique o relatório.";
              echo;
            fi
            echo "### Relatórios anexados";
            echo "- Playwright: artifact 'playwright-report' (abra index.html)";
            echo "- Cucumber HTML customizado: artifact 'cucumber-html' (arquivo cucumber-html-report.html)";
            echo "- Cucumber JSON: artifact 'cucumber-json'";
          } >> $GITHUB_STEP_SUMMARY
